name: protoc-publish-image
on:
  push:
    tags:
      - 'v*'
jobs:
  main:
    name: Checkout code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Build and push Docker image
        uses: docker/build-push-action@v1
        with:
          build_args: GIT_REF=${GITHUB_REF}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: justarchi/protoc
          tags: latest
          tag_with_ref: true
          username: ${{ secrets.DOCKER_USERNAME }}
