name: protoc-publish-image
on:
  release:
    types: [published]
jobs:
  main:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Push to Docker Hub
        uses: docker/build-push-action@v1
        with:
          build_args: PROTOC_VERSION=${{ github.event.release.tag_name }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: justarchi/protoc
          tags: latest
          tag_with_ref: true
          username: ${{ secrets.DOCKER_USERNAME }}
